---
# Stackmate project configuration
framework: rails
# The repository to deploy from
repository: git@github.com:stackmate-io/sample-app-rails.git
# The cloud provider to use
provider: aws
# The region to deploy to
region: eu-central-1
# The provider credentials to use
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
  github:
    access_key: "{{ lookup('env', 'STACKMATE_GITHUB_ID') }}"
    secret: "{{ lookup('env', 'STACKMATE_GITHUB_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_GITHUB_TOKEN') }}"
  slack:
    secret: "{{ lookup('env', 'STACKMATE_SLACK_TOKEN') }}"
  email:
    host: smtp.sendgrid.net
    port: 587
    access_key: apikey
    secret: "{{ lookup('env', 'STACKMATE_SENDGRID_TOKEN') }}"

# environments
production:
  # branch to deploy
  branch: master
  # domain to use
  domain: rails.ezploy.eu
  # documentroot in the servers
  documentroot: /var/www/rails-app

  # environment variables
  environment:
    CDN_HOST: cdn.ezploy.eu
    RAILS_ENV: production
    SECRET_KEY_BASE: 78e078fd223a2904d26de6b1d46a8418

  # configfiles:
  #   - source: production.master.key
  #     target: config/master.key
  #     application: true

  # deployment pipeline
  pipeline:
    build:
      - ./bin/bundle config cache_path /var/www/rails-app/cache
      - ./bin/bundle package --all
      - ./bin/bundle install --local --deployment --without development test --jobs 5
      - ./bin/rails assets:precompile
    db:migrate:
      - ./bin/rails db:migrate
    after:
      restart:
        - puma
        - sidekiq
      reload:
        - nginx

  statics:
    - source: public/assets
      bucket: rails-assets-ezploy-eu

  # services to use
  services:
    - name: rails-app-server
      type: application
      size: t2.micro
      dependencies:
        - type: ruby
          version: 2.5.8
          bundler: 1.16.6
        - type: puma
          configfile: config/puma.rb
          port: 3000
        - type: nginx
        - type: sidekiq
          configfile: config/sidekiq.yml
        - type: nodejs
      storage: 20

    - name: rails-postgres-db
      type: postgresql
      version: '10.10'
      size: db.t3.micro
      storage: 20
      databases:
        - railsapp
      environment:
        POSTGRES_DB: railsapp
        POSTGRES_USER: "{{username}}"
        POSTGRES_HOST: "{{host}}"
        POSTGRES_PASSWORD: "{{password}}"
        POSTGRES_PORT: "{{port}}"

    - name: rails-redis-cache
      type: redis
      size: cache.t2.micro
      environment:
        REDIS_URL: 'redis://{{host}}:{{port}}/1'

    - name: mailer
      type: mailer
      domain: rails.ezploy.eu
      environment:
        ACCESS_KEY: '{{username}}'
        ACCESS_SECRET: '{{secret}}'

    - type: elasticstorage
      name: rails-assets-ezploy-eu
      public: true
      cdn: true
      domain: cdn.ezploy.eu

# notifications:
#   - type: email
#     targets:
#       - stackmateuser@mailinator.com

#   - type: slack
#     targets:
#       - deployments-channel
