development: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: railsapp_dev

test:
  adapter: test

production:
  <<: *default
  channel_prefix: railsapp_production
